seerver.port= ${PORT:8080}

spring.application.name=servidorlocal

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/servidorlocal}
spring.datasourece.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

server.max-http-header-size=128KB
server.tomcat.max-http-from-post-size=2MB

spinng.h2.console.enabled=true

# Configurações do Servidor de Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nilsonjoao647@gmail.com
spring.mail.password=ibtl bnws hkkr botb

#Configurações avançadas de segurança exigidas pelo Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




